### PR TITLE
Add failing endpoint address classifier

### PR DESCRIPTION
**Pull request by WilliamBZA**
## Who's affected

* Any user using Service Control to manage errors

## Symptoms

Adds an additional classifier to group errors based on the address of the endpoint.

## Original request 

https://github.com/Particular/ServicePulse/issues/427

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Ping @Particular/servicecontrol-maintainers. There shouldn't be a practical issues here, but I wonder how far down the rabbit hole of "what classifiers should we add" can we go before it becomes an extensability problem.

Perhaps we should split these extensions out to a plugin-type model? Or allow for enabling/disabling classifiers?

**Comment by SzymonPobiega** [comment]
@WilliamBZA does this require an automated test or are we sure it will be automatically discovered and "just work"?

**Comment by WilliamBZA** [comment]
Good catch @SzymonPobiega. I didn't update the test

**Comment by SzymonPobiega** [comment]
@WilliamBZA I don't like these "magic" functions where you just need to add a class and it will be automatically picked up. Hard to tell if the code is working just by looking at the text.

**Comment by WilliamBZA** [comment]
It's actually not only missing the test, it's also missing the container configuration - which would have made it more explicit that we're registering a grouper.

I've fixed both.

**Comment by SzymonPobiega** [comment]
LGTM @WilliamBZA . Do you want it merged?

**Comment by WilliamBZA** [comment]
Thanks @SzymonPobiega. I'll merge and release with 1.39.0

**Pull request merged**
