### PR TITLE
Handling failures when publishing to external integrations

### PR DESCRIPTION
**Pull request by johnsimons**
If the publishing of an event to external integrations fails continuosly, SC is shutdown.

This PR catches exceptions as part of the publishing, logs them in the log file and also adds them to the append log that SC keeps and is displayed in SP.

### CODE REVIEW

**Comment by johnsimons** [comment]
@mikeminutillo @DavidBoike thoughts ?

**Comment by mikeminutillo** [comment]
Does the exception thrown indicate which endpoint was the problem?

**Comment by johnsimons** [comment]
@mikeminutillo nope, we don't know, we don't have that info, hopefully the exception message will say

**Comment by DavidBoike** [comment]
Not a huge fan. Unlikely they'll subscribe to the new event. There's a lot of samples and doco out there (not all controlled by us) about how to subscribe to SC events and this isn't mentioned. So SC is not falling over, which is good, but *much* higher likelihood of complete and total message loss, because a Publish to 0 subscribers leaves absolutely no trace.

But at least SC doesn't fall over. :smile:

**Comment by johnsimons** [comment]
@DavidBoike in this proposal I am logging the exception into two different locations.
- the log fie, which we tend to tell the users to monitor, but being an app maybe not the right place;
- logging to the append only log in SC, which gets displayed in SP for the user to take action. We also use this same technique for other areas of SC where things fail and we need to notify the user.

**Pull request merged**
