### PR TITLE
Allow installing of single instance type from SCMU

### PR DESCRIPTION
**Pull request by WilliamBZA**
Fixes https://github.com/Particular/ServiceControl/issues/2956
Fixes https://github.com/Particular/ServiceControl/issues/2960

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Adds checkboxes to select which instance type to install

image

**Review by awright18 — APPROVED** [review]

**Comment by bording** [comment]
This seems to assume that at least one checkbox is checked when you click the Add button.

When I unchecked both and then clicked Add, I got a `NullReferenceException`.

Seems like we need some protection around having nothing selected.

**Comment by WilliamBZA** [comment]
I've update this. It validates that at least one instance type is selected.

It also fixes the validation messages [not being displayed on the controls](https://github.com/Particular/ServiceControl/issues/2960).

**Review by awright18 — APPROVED** [review]
LGTM

**Review by bording — APPROVED** [review]

**Comment by udidahan** [comment]
As a potential user reading the text of those checkboxes, I'm not sure I'd intuitively understand the different between "ServiceControl" and "ServiceControl Audit". Is there something we could do to make this clearer?

**Comment by WilliamBZA** [comment]
@udidahan The wording was there before this PR and wasn't changed here, but I agree that it's something that should be made clearer. Do you know if there's already an issue tracking that?

**Comment by udidahan** [comment]
I don't know.

**Comment by WilliamBZA** [comment]
I created a [follow-up issue](https://github.com/Particular/ServiceControl/issues/3278) to try make the use of names clearer.

**Pull request merged**
