### PR TITLE
Fix run as service introduced by  and logging initialization vs configuration order

### LINKED ISSUE #2017: Log to console no longer working
Copied from https://github.com/Particular/ServiceControl/pull/2002#issuecomment-631172332

> Hey @WilliamBZA ,
> 
> At this point i don't think it works with docker as it looks like things are worse.  
> 
> I got the release with the fix ( 4.9.0) and i see nothing being reported in stdout.  I also no longer see anything printing to my powershell console when i run servicecontrol fior audit/error import. 
> 
> Before
> 
> image
> 
> 
> After
> 
> image
> 
> 
> I tried adding the --portable flag and still saw nothing

### LINKED ISSUE #2031: Strange Behavior in v4.9.0
Hey Guys,

It looks like there is something strange that got introduced in v4.9.0.  When you try and start an instance a few seconds after you stopped it it will fail to start.  Below is the servicecontrol log that contains nothing but info.

```
2020-05-31 23:56:52.5306|1|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
2020-05-31 23:56:53.2037|1|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Loading Embedded RavenDB license
2020-05-31 23:56:54.8076|1|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Index creation started
2020-05-31 23:56:58.6181|1|Info|NServiceBus.LicenseManager|Selected active license from C:\ProgramData\ParticularSoftware\license.xml
License Expiration: 202X-0X-X
2020-05-31 23:56:59.2912|4|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
2020-05-31 23:56:59.6301|4|Info|Particular.ServiceControl.Bootstrapper|
-------------------------------------------------------------
ServiceControl Version:             4.9.0+0.Branch.release-4.9.Sha.05662e568bdb5b7f9170dbdd7653480d921596c7
Audit Retention Period (optional):  
Error Retention Period:             15.00:00:00
Ingest Error Messages:              True
Forwarding Error Messages:          False
Database Size:                      1056768 bytes
ServiceControl Logging Level:       Info
RavenDB Logging Level:              Warn
Selected Transport Customization:   ServiceControl.Transports.RabbitMQ.RabbitMQConventionalRoutingTransportCustomization, ServiceControl.Transports.RabbitMQ
-------------------------------------------------------------
2020-05-31 23:56:59.9351|4|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Loading Embedded RavenDB license
2020-05-31 23:57:01.8971|4|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Index creation started
2020-05-31 23:57:03.0683|4|Info|NServiceBus.LicenseManager|Selected active license from C:\ProgramData\ParticularSoftware\license.xml
License Expiration: 202X-XX-XX
2020-05-31 23:57:03.3761|23|Info|ServiceControl.Recoverability.RetryDocumentManager|Found 0 orphaned retry batches from previous sessions.
2020-05-31 23:57:03.4051|12|Info|ServiceControl.Recoverability.RetryProcessor|No batch found to forward.
2020-05-31 23:57:03.4771|23|Info|ServiceControl.Recoverability.RetryProcessor|No batch found to stage.
2020-05-31 23:57:03.7811|13|Info|Particular.ServiceControl.Bootstrapper|Api is now accepting requests on http://localhost:33333/api
2020-05-31 23:57:13.6272|4|Info|NServiceBus.RunningEndpointInstance|Initiating shutdown.
2020-05-31 23:57:13.6672|4|Info|NServiceBus.Raw.RunningRawEndpointInstance|Stopping receiver.
2020-05-31 23:57:13.6712|4|Info|NServiceBus.Raw.RunningRawEndpointInstance|Receiver stopped.
2020-05-31 23:57:13.6712|4|Info|NServiceBus.Raw.StoppableRawEndpoint|Initiating shutdown.
2020-05-31 23:57:13.6712|4|Info|NServiceBus.Raw.StoppableRawEndpoint|Shutdown complete.
2020-05-31 23:57:13.8302|4|Info|NServiceBus.RunningEndpointInstance|Shutdown complete.
2020-05-31 23:57:13.8502|1|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
2020-05-31 23:57:13.8502|1|Info|Particular.ServiceControl.Bootstrapper|
-------------------------------------------------------------
ServiceControl Version:             4.9.0+0.Branch.release-4.9.Sha.05662e568bdb5b7f9170dbdd7653480d921596c7
Audit Retention Period (optional):  
Error Retention Period:             15.00:00:00
Ingest Error Messages:              True
Forwarding Error Messages:          False
Database Size:                      1056768 bytes
ServiceControl Logging Level:       Info
RavenDB Logging Level:              Warn
Selected Transport Customization:   ServiceControl.Transports.RabbitMQ.RabbitMQConventionalRoutingTransportCustomization, ServiceControl.Transports.RabbitMQ
-------------------------------------------------------------
2020-05-31 23:57:13.8772|1|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Loading Embedded RavenDB license
2020-05-31 23:57:14.2732|1|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Index creation started
2020-05-31 23:57:14.4033|1|Info|NServiceBus.LicenseManager|Selected active license from C:\ProgramData\ParticularSoftware\license.xml
License Expiration: 202X-XX-XX
2020-05-31 23:57:14.4362|41|Info|ServiceControl.Recoverability.RetryProcessor|No batch found to forward.
2020-05-31 23:57:14.4362|13|Info|ServiceControl.Recoverability.RetryDocumentManager|Found 0 orphaned retry batches from previous sessions.
2020-05-31 23:57:14.4362|13|Info|ServiceControl.Recoverability.RetryProcessor|No batch found to stage.
2020-05-31 23:57:14.4702|28|Info|Particular.ServiceControl.Bootstrapper|Api is now accepting requests on http://localhost:33333/api
2020-05-31 23:57:15.8782|4|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
2020-05-31 23:57:16.2472|4|Info|Particular.ServiceControl.Bootstrapper|
-------------------------------------------------------------
ServiceControl Version:             4.9.0+0.Branch.release-4.9.Sha.05662e568bdb5b7f9170dbdd7653480d921596c7
Audit Retention Period (optional):  
Error Retention Period:             15.00:00:00
Ingest Error Messages:              True
Forwarding Error Messages:          False
Database Size:                      1056768 bytes
ServiceControl Logging Level:       Info
RavenDB Logging Level:              Warn
Selected Transport Customization:   ServiceControl.Transports.RabbitMQ.RabbitMQConventionalRoutingTransportCustomization, ServiceControl.Transports.RabbitMQ
-------------------------------------------------------------
2020-05-31 23:57:16.6162|4|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Loading Embedded RavenDB license
2020-05-31 23:57:27.1062|1|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
2020-05-31 23:57:27.1102|1|Info|Particular.ServiceControl.Bootstrapper|
-------------------------------------------------------------
ServiceControl Version:             4.9.0+0.Branch.release-4.9.Sha.05662e568bdb5b7f9170dbdd7653480d921596c7
Audit Retention Period (optional):  
Error Retention Period:             15.00:00:00
Ingest Error Messages:              True
Forwarding Error Messages:          False
Database Size:                      1056768 bytes
ServiceControl Logging Level:       Info
RavenDB Logging Level:              Warn
Selected Transport Customization:   ServiceControl.Transports.RabbitMQ.RabbitMQConventionalRoutingTransportCustomization, ServiceControl.Transports.RabbitMQ
-------------------------------------------------------------
2020-05-31 23:57:27.1342|1|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Loading Embedded RavenDB license
```

Looking at the ravendb logs i see the following errors which seem to be related to the issue.

```
2020-05-31 23:56:55.5406|12|Warn|Raven.Client.Connection.Async.AsyncServerClient|Was unable to fetch topology from primary node http://localhost also there is no cached topology
2020-05-31 23:57:02.3561|13|Warn|Raven.Client.Connection.Async.AsyncServerClient|Was unable to fetch topology from primary node http://localhost also there is no cached topology
2020-05-31 23:57:27.0812|4|Error|Raven.Database.Server.RavenDBOptions|Found errors in the system database while loading it for the first time.
                                    This is recoverable error, since we will simply ingore transactions after the faulted one.
Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cannot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Api.JetInit(JET_INSTANCE& instance)
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs, Action`1 putResourceMarker, Action`2 onErrorAction)
2020-05-31 23:57:27.0812|4|Error|Raven.Database.DocumentDatabase|Could not initialize transactional storage, not creating database
System.InvalidOperationException: Could not write to location: C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\DB\. Make sure you have read/write permissions for this path. ---> Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cannot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Api.JetInit(JET_INSTANCE& instance)
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs, Action`1 putResourceMarker, Action`2 onErrorAction)
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs, Action`1 putResourceMarker, Action`2 onErrorAction)
   at Raven.Database.DocumentDatabase.DocumentDatabaseInitializer.InitializeTransactionalStorage(IUuidGenerator uuidGenerator, Action`2 onErrorAction)
   at Raven.Database.DocumentDatabase..ctor(InMemoryRavenConfiguration configuration, DocumentDatabase systemDatabase, TransportState recievedTransportState, Action`2 onError)
2020-05-31 23:57:37.1582|1|Error|Raven.Database.Server.RavenDBOptions|Found errors in the system database while loading it for the first time.
                                    This is recoverable error, since we will simply ingore transactions after the faulted one.
Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cannot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Api.JetInit(JET_INSTANCE& instance)
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs, Action`1 putResourceMarker, Action`2 onErrorAction)
2020-05-31 23:57:37.1582|1|Error|Raven.Database.DocumentDatabase|Could not initialize transactional storage, not creating database
System.InvalidOperationException: Could not write to location: C:\ProgramData\Particular\ServiceControl\Particular.ServiceControl\DB\. Make sure you have read/write permissions for this path. ---> Microsoft.Isam.Esent.Interop.EsentFileAccessDeniedException: Cannot access file, the file is locked or in use
   at Microsoft.Isam.Esent.Interop.Api.JetInit(JET_INSTANCE& instance)
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs, Action`1 putResourceMarker, Action`2 onErrorAction)
   --- End of inner exception stack trace ---
   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator, OrderedPartCollection`1 documentCodecs, Action`1 putResourceMarker, Action`2 onErrorAction)
   at Raven.Database.DocumentDatabase.DocumentDatabaseInitializer.InitializeTransactionalStorage(IUuidGenerator uuidGenerator, Action`2 onErrorAction)
   at Raven.Database.DocumentDatabase..ctor(InMemoryRavenConfiguration configuration, DocumentDatabase systemDatabase, TransportState recievedTransportState, Action`2 onError)
```

It would be awesome if someone can also verify this behavior.

### PR DESCRIPTION
**Pull request by ramonsmits**
Fixes #2031
Fixes #2002
Fixes #2017

User reported in #2031 that windows service control manager behaved strangely. Testing this indicated it was not run as a service resulting in this strange behavior. While fixing this I noticed that logging was initialized early while 'the print to console' setting was set after logging was already initialized.

### CODE REVIEW

**Comment by danielmarbach** [comment]
@ramonsmits unfortunately this probably requires a rebase now

**Comment by TraGicCode** [comment]
Hey @ramonsmits ,

Any updates on this?  is this still on the radar for your team?

Thank you!

**Comment by ramonsmits** [comment]
> Any updates on this? is this still on the radar for your team?

@TraGicCode We have reverted the behavior of the hosting and logging at the last related change broke hosting and logging. We provided a workaround to log to console by providing an `NLog.config`. Due to that, this specific enhancement gets a lower priority but we will eventually address it.

**Comment by TraGicCode** [comment]
> > Any updates on this? is this still on the radar for your team?
> 
> @TraGicCode We have reverted the behavior of the hosting and logging at the last related change broke hosting and logging. We provided a workaround to log to console by providing an `NLog.config`. Due to that, this specific enhancement gets a lower priority but we will eventually address it.

Thanks for replying,  I will give that a shot and see if i have any issues

**Comment by tmasternak** [comment]
Hi, @TraGicCode I'm trying to figure out what is the scenario that you need the custom `nlog.config`. Could you share a bit more about when is it that ServiceControl doesn't log to the console and custom configuration is needed?

**Comment by TraGicCode** [comment]
Hey @tmasternak ,

sorry for getting back to you so late. My puppet module for servicecontrol has a task that allows someone to automatically re-import failed audit and error messages. Unfortunately servicecontrol was logging but not logging to stdout which is what puppet uses to display output back to the user.  @ramonsmits revommended above I needed to customize nlog for this to happen.  Do you know if this is still required?

**Comment by tmasternak** [comment]
Hi @TraGicCode,

In the latest version, ServiceControl logs to the console when executing an error or audit messages re-import.

**Comment by TraGicCode** [comment]
Hey @tmasternak ,

Let me test this and get back with my results.

**Comment by TraGicCode** [comment]
Hey @tmasternak ,

Everything appears to be working fine for me.  Thanks!

**Comment by tmasternak** [comment]
Glad to hear that :). Thank you for verification @TraGicCode.

**Pull request closed without merging**
