### PR TITLE
Workaround for az bug

### PR DESCRIPTION
**Pull request by andreasohlund**
Can be removed once https://github.com/Azure/azure-cli/issues/26272#issuecomment-1534158361 is merged and release

### CODE REVIEW

**Comment by andreasohlund** [comment]
🍿

**Comment by WilliamBZA** [comment]
Should we merge this PR only into the release branch so that we don't forget to remove it once MS fixes?

**Comment by andreasohlund** [comment]
>Should we merge this PR only into the release branch so that we don't forget to remove it once MS fixes?

Good idea, I have retargeted

All green 🔥

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/ServiceControl/pull/3509

**Pull request closed without merging**
