### PR TITLE
Added borders to controls

### LINKED ISSUE #542: Should textboxes be more prominent/standard ?
image

The current styling used for the textboxes is concerning IMO, it is not the standard bordered rectangle.
Looking at the main audience for this tool (OPS) and the machines they will be running this tool on (servers with low resolutions), will these users be able to identify the proposed textboxes ?

I recommend at least to add the four borders to the styling to make it more "standard".

### PR DESCRIPTION
**Pull request by johnsimons**
Added borders to controls
Increased the padding

Fixes #542

### CODE REVIEW

**Comment by johnsimons** [comment]
@gbiellem @distantcam Had a go at fixing #542.

Can someone review ?

Also need help making the pick buttons the same height as textbox.

image

**Comment by gbiellem** [comment]
Looks good to me. Fixed the height on those buttons. 

capture

**Comment by gbiellem** [comment]
@distantcam can you please look it and merge it if you are happy.

**Comment by sergioc** [comment]
Nice attention to detail @johnsimons and @gbiellem !

**Comment by distantcam** [comment]
This looks good to me. Why are there build errors?

**Comment by johnsimons** [comment]
No idea @distantcam, the only changes are in the xaml file

**Pull request merged**
