### PR TITLE
Added metrics

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Added Metrics.NET library for capturing important metrics (e.g. audit ingestion throughput)

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/engineers please review. Especially the fact that I am using an external library (Metrics.NET - a port of Java Metrics lib developed by Codahale)

**Comment by SzymonPobiega** [comment]
@sergioc @andreasohlund I think the bot is doing strange things in your behalf. Look at the history of this issue. You might want to check if it didn't take some loans acting as you

**Comment by sergioc** [comment]
@SzymonPobiega @andreasohlund I definitely did not add that label :-)

**Comment by andreasohlund** [comment]
It's the waffle.io integration that does this

**Pull request merged**
