### PR TITLE
Added CustomCheckSucceeded and CustomCheckFailed event publishing for external integration

### PR DESCRIPTION
**Pull request by johnsimons**
This requirement was originally raised in https://github.com/Particular/Requirements/issues/136

### CODE REVIEW

**Comment by johnsimons** [comment]
@SzymonPobiega can u check this one up to make sure I created the events publishing correct?
It seems to be working!

**Comment by gbiellem** [comment]
@johnsimons  The event publishing looks like it's the same as heartbeats so :+1:  to merge.  Is their any doco changes to go with it?

**Comment by johnsimons** [comment]
Yeah, I'll update the docs once it is out

**Comment by gbiellem** [comment]
@johnsimons  - SC 1.5 is now released with this change in it.  Doco?

**Comment by johnsimons** [comment]
@gbiellem awesome news, thank you.

Doco is done too

**Pull request merged**
