### PR TITLE
Revert "Merge pull request #2000 from Particular/logging-to-console"

### PR DESCRIPTION
**Pull request by danielmarbach**
Backport of #2045 to `release-4.10` branch

This reverts commit 05662e568bdb5b7f9170dbdd7653480d921596c7, reversing
changes made to 0e593f007e5f5f0fe4360dfb04483761057168a5.

### CODE REVIEW

**Comment by JSCProjects** [comment]
After installing this new version I still get the following error:

System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Particular Software\Particular.ServiceControl.Audit\Autofac.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at ServiceControlInstaller.Engine.FileSystem.FileUtils.DeleteDirectory(String path, Boolean recursive, Boolean contentsOnly, String[] excludes)
   at ServiceControlInstaller.Engine.Instances.ServiceControlAuditInstance.UpgradeFiles(String zipFilePath)
   at ServiceControl.Config.Framework.Modules.ServiceControlInstallerBase.Upgrade(ServiceControlBaseService instance, ServiceControlUpgradeOptions upgradeOptions, IProgress`1 progress)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Commands.UpgradeAuditInstanceCommand.<UpgradeAuditInstance>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Commands.UpgradeAuditInstanceCommand.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Framework.Commands.AwaitableAbstractCommand`1.<ServiceControl-Config-Framework-Commands-ICommand<T>-Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ramonsmits** [comment]
@JSCProjects that probably is due to the bug. The process is still running after a service stop resulting in the files to be locked.

Could you stop, wait at least 30 seconds, and then update?

**Comment by JSCProjects** [comment]
Yeah that's normally my workaround, this morning something strange happened. The servicecontrol installer dropped all the binaries and showed us a running system, but after an hour I get complaints about that there were messages missing. So I've copied the files from other server and upgraded to v4.10.2.

**Comment by ramonsmits** [comment]
> The servicecontrol installer dropped all the binaries

@JSCProjects what do you mean with this? Deployed/installed?

I'm assuming missing messages visualized in ServicePulse due to the service not running?

**Pull request merged**
