### PR TITLE
Subscribe to own events AFTER Installers have run

### PR DESCRIPTION
**Pull request by mikeminutillo**
Connects to #586 

Subscribing to own events must wait for Installers to run

### CODE REVIEW

**Comment by johnsimons** [comment]
looks good :+1:

**Comment by mikeminutillo** [comment]
This has passed all the acceptance tests on the build server. 

@johnsimons do we want to release this? It *should* have no impact other than on the acceptance tests.

**Comment by johnsimons** [comment]
:+1: 
To just merge, no need to release

**Comment by mikeminutillo** [comment]
Merged to `develop` and `master`.

**Pull request merged**
