### PR TITLE
MessageForwarder resets TTBR if present

### PR DESCRIPTION
**Pull request by danielmarbach**
The previous version did a reset of the TTBR, see

https://github.com/Particular/ServiceControl/blob/33b4e74e7357e3daef5f16ebe80dbc56f3a7b461/src/ServiceControl/Operations/ErrorQueueImport.cs#L160
and
https://github.com/Particular/ServiceControl/blob/7f46be452a66877eca8c960e545c46dee40c16f3/src/ServiceControl/Operations/AuditQueueImport.cs#L105

See documented core behavior https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Headers.cs#L221-L222

This does it now consistently in the forwarder and removes the TODO

### CODE REVIEW

**Comment by danielmarbach** [comment]
The previous code always set the TimeToBeReceived property which did not set a header but was used by the transport. So effectively we can say the TimeToBeReceived was always set to `TimeSpan.Max`. The question is should we always set the header as well and therefore even remove the `if(headers.ContainsKey())` part?

**Comment by danielmarbach** [comment]
Given that forwarded messages should last as long as possible and the previous version did always set the TimeToBeReceived property I'm now always setting the TTBR header since this is the replacement in the modern core for TimeToBeReceived property.

**Comment by mikeminutillo** [comment]
I think the previous implementation set the property to MAX because it was not nullable. We don't get a TTBR property on incoming messages anymore. Shouldn't we just remove the header, if present?

**Comment by danielmarbach** [comment]
That is one way to look at it. Another perspective is to look at the
semantics that was there. Setting it to maxvalue means "lives forever".
With the property beikg replaced by TTBR header the semantic replacement
woulf be to set the header to maxvalue. If no TTBR header is available it
means "lives forever" we can definitely remove the header if present

**Comment by danielmarbach** [comment]
Update the PR to remove the header if present. @Particular/servicecontrol-maintainers please review and merge

**Pull request merged**
