### PR TITLE
Enabling incremental backups

### PR DESCRIPTION
**Pull request by johnsimons**
A quick spike to enable incremental backups.

This is quite easy to get going.

The next steps would be to as part of a new instance install ask the user the location for the backups and frequency.

This is related to #759

### CODE REVIEW

**Comment by johnsimons** [comment]
Adding a couple of extra questions to the install ui shouldn't take a long time, we then store those settings in the config file and we read them out of there.

Regarding turning this on for an existing database, I tested it and it does add a bit of pressure because I assume it is doing a full backup to start with.

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers thoughts ?

**Comment by mauroservienti** [comment]
well enabling incremental backups is absolutely a nice addition, allows customers to save space and increase data security running backups more frequently. We should test a disaster recovery as well before implementing this.

**Comment by gbiellem** [comment]
@mauroservienti 

>  allows customers to save space 

How does it save space?  Surely it's using more space.  

@johnsimons  

Are you proposing this as an alternative to the idea of offering the user the option to do a complete backup on upgrades?

**Comment by mauroservienti** [comment]
If the only option is a full backup and you need to retain deletions you must preserve multiple full backups leading to more wasted space compared to the incremental solution. Isn't it?

**Comment by johnsimons** [comment]
Will re-evaluate this when we go Raven v3

**Pull request closed without merging**
