### PR TITLE
Hostname fields no longer accept IP addresses

### PR DESCRIPTION
**Pull request by awright18**
Fixes 
- #3503

### CODE REVIEW

**Comment by cquirosj** [comment]
Great to have test coverage now for the addition of up addresses!
Do we have tests for the old behavior too? Like hostnames, http://+  and http://* ? I am not sure but I think those are also supported behaviors.

**Review by soujay — APPROVED** [review]

**Comment by mauroservienti** [comment]
@awright18 in #3528, we fixed a build-related issue causing the Azure tests to fail. If you rebase, it should be green.

**Comment by awright18** [comment]
@mauroservienti I rebased, and I'm now seeing tests failing for manifest-related issues. Would you mind taking a look at the [CI results](https://github.com/Particular/ServiceControl/actions/runs/5069878011)

**Comment by mauroservienti** [comment]
It's a race condition in the build artifacts we thought we had fixed; it looks like it's not the case. We'll further investigate.

**Comment by mauroservienti** [comment]
#3542 is merged. You can rebase, it should work now 🤞😆

**Pull request merged**
