### PR TITLE
Event broadcast not working

### PR DESCRIPTION
**Pull request by mikeminutillo**
Connects to #590

SignalR was resolving a separate connection when broadcasting messages. This meant that successfully connected clients were not receiving messages.

### CODE REVIEW

**Comment by johnsimons** [comment]
@mikeminutillo this looks good to me :+1:

**Comment by johnsimons** [comment]
@mikeminutillo have added test coverage, can u review ?

@mikeminutillo @andreasohlund 
I have only tested one single signalrr event, do you think that is enough or do we test them all ?

**Comment by mikeminutillo** [comment]
@johnsimons The test looks good for testing the infrastructure. We should raise a separate issue to test the "public api" of the SignalR integration point. That is, every event that Pulse (the only consumer) relies on, we should check to ensure that it gets raised and that it contains the expected data in the expected format.

**Comment by johnsimons** [comment]
Merged as part of hotfix-1.7.5

**Pull request closed without merging**
