### PR TITLE
revert expiry index

### PR DESCRIPTION
**Pull request by SimonCropp**
so as to not create startup load

### CODE REVIEW

**Comment by SimonCropp** [comment]
@mikeminutillo @johnsimons based on both your input i have reverted back the message expiry index so as to not cause load

**Comment by johnsimons** [comment]
So are we doing a standalone expiry for saga histories ?

**Comment by SimonCropp** [comment]
@johnsimons since u said u didnt want the load caused by changing the expiry message index

**Comment by johnsimons** [comment]
No worries @SimonCropp 
So is the new expiration for saga histories to go out as par of 1.7 release ?

**Comment by johnsimons** [comment]
:+1: to merge

**Comment by mikeminutillo** [comment]
Looks good to me as well :+1:

**Pull request merged**
