### PR TITLE
Pass message session to the failed audits component

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
I found this one on 4.18 but I am pretty sure it is much older than that. Anyway, we need someone to review it ;-) I'll raise the KTLO issue for it.

**Review by WilliamBZA — APPROVED** [review]
Should we try add a test to catch this in the future?

**Comment by SzymonPobiega** [comment]
@WilliamBZA I'll see if we can do it in the new version that we work on. This is not trivial because the acceptance tests currently don't exercise commands, they start on the lever below.

**Review by mikeminutillo — APPROVED** [review]

**Review by tmasternak — APPROVED** [review]

**Comment by mikeminutillo** [comment]
@SzymonPobiega is this still needed now that 4.19 is out?

**Comment by SzymonPobiega** [comment]
@mikeminutillo you are right, no longer needed because it is fixed in the latest.

**Pull request closed without merging**
