### PR TITLE
Api facade rebased

### PR DESCRIPTION
**Pull request by boblangley**
We merged `api-facade` #1069 without rebasing on master. We reverted that commit, but needed to build this new PR with a rebase from the correct commit 7f46be452a66877eca8c960e545c46dee40c16f3, the latest commit before #1069 was pre-maturely merged.

### CODE REVIEW

**Comment by boblangley** [comment]
We confirmed this is correct by manually merging locally first. We also did a File/Folder comparison using Beyond Compare between the branches in addition to GIT DIFFS.

**Comment by danielmarbach** [comment]
Sorry what was prematurely merged and why was the revert needed?

**Comment by danielmarbach** [comment]
Btw love that we finally have this in! Great collaboration!

**Comment by SeanFeldman** [comment]
> Sorry what was prematurely merged and why was the revert needed?

That was our issue (@boblangley and I). We merged the original PR w/o rebasing it first on `master` 😊
Fixed now.

> Btw love that we finally have this in! Great collaboration!

Share the sentiment!

**Pull request merged**
