### PR TITLE
Archiving by index

### PR DESCRIPTION
**Pull request by johnsimons**
This relates to #650

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers so now the question is what do we report on ?

```c#
Bus.Publish<FailedMessageGroupArchived>(m =>
            {
                m.GroupId = message.GroupId;
                m.GroupName = message.GroupId;
                m.MessageIds = new []{ result.ToString() };
            });
```

As @ramonsmits and @mauroservienti point out, there is no point inreporting on a massive list of ids, so do we get rid of it ?

**Comment by mikeminutillo** [comment]
We probably don't want to have 100s of thousands of ids in there but it's not that difficult to get.

```CSharp
var result = operation.WaitForCompletion();
	
var updatedDocuments = result.JsonDeserialization<DocumentPatchResult[]>();
var updatedIds = updatedDocuments.Select(x => x.Document).ToArray();

public class DocumentPatchResult
{
	public string Document { get; set; }
	public Results Result { get; set; }
	public string[] Debug { get; set; }

	public class Results
	{
		public string PatchResult { get; set; }
		public string Document { get; set; }
	}
}
```

**Comment by mikeminutillo** [comment]
Now capturing the group name and related failed message Ids correctly. I suspect we want to get rid of the message Ids but we need to discuss the impact that will have first.

**Comment by mikeminutillo** [comment]
Added an explicit cutoff date. Without this cutoff the call to `UpdateByIndex()` will fail under high load. The other alternative is that we can explicitly allow Stale Indexes.

**Comment by mauroservienti** [comment]
Which the reason we report the `message ids` other than the `group id`? We are archiving a group in the end.

> Without this cutoff the call to UpdateByIndex() will fail under high load. The other alternative is that we can explicitly allow Stale Indexes.

Interesting, do you remember the error?
cause when we tried that the load was super heavy and it worked as expected.

**Comment by johnsimons** [comment]
I have modified the UpdateByIndex query to allowStale = true, otherwise we could block for a long time.

**Comment by mikeminutillo** [comment]
> Interesting, do you remember the error?
> cause when we tried that the load was super heavy and it worked as expected.

If the index is stale the update should fail and throw an exception. If the index is keeping up then it shouldn't be a problem.

**Comment by johnsimons** [comment]
I have removed the list of guids and instead we just display the total count.
@Particular/servicecontrol-maintainers anything else that needs to be done here before merging ?

**Pull request closed without merging**
