### PR TITLE
Using patch api to update heartbeats

### PR DESCRIPTION
**Pull request by johnsimons**
This PR uses the patch api to update heartbeats.

This saves us from having to do a read.

### CODE REVIEW

**Comment by johnsimons** [comment]
@mikeminutillo this is a small but hopefully significant improvement.
I know is not exactly what you described in #639, but given the difficulty to pull off #639 as described and also given that we know we want to split out heartbeats and rearchitect it from the ground up, I wonder if this PR is a good alternative for now ?

@Particular/servicecontrol-maintainers thoughts ?

**Comment by ramonsmits** [comment]
:+1: Good improvement, reduced API calls by 50% regarding heartbeat updates. 

Issie with #639 is also that the SQL transport does a lousy job regarding expired messages.

**Comment by adamralph** [comment]
Any functional change here or just a refactoring?

**Comment by johnsimons** [comment]
@adamralph just a change how we update documents

**Comment by adamralph** [comment]
@johnsimons @gbiellem thanks, if no functional change then refactoring label makes sense.

**Comment by johnsimons** [comment]
Actually this is just an improvement, a label that is missing

**Comment by johnsimons** [comment]
Merged into release-1.11

**Pull request closed without merging**
