### PR TITLE
Spike Routed API approach

### PR DESCRIPTION
**Pull request by mikeminutillo**
Based on my review of #1082

### CODE REVIEW

**Comment by danielmarbach** [comment]
I'm good with that approach since it is also more intention revealing. My original question from the PR remains: Do we need it since we are removing the ListSagasAPI?

**Comment by SzymonPobiega** [comment]
Isn't the main point of this feature to be able to retry messages from SI?

**Comment by mikeminutillo** [comment]
@SzymonPobiega yes. The Retry POST is where we need it.

**Comment by danielmarbach** [comment]
@SzymonPobiega @mikeminutillo not exactly. The base class here assumes querying of either local or remote. As it currently stands the decision was to send messages to remote and not call the API with forwarding, see https://github.com/Particular/ServiceControl/blob/api-facade/src/ServiceControl/MessageFailures/Api/RetryMessages.cs#L20 

@mikeminutillo are you proposing to switch to API forwarding then?

**Comment by SzymonPobiega** [comment]
@danielmarbach yeah. I forgot about that. So in this case I propose to keep the current solution, delete the `ListSagas` API and park this SPIKE until we discover an API that needs it.

**Comment by SzymonPobiega** [comment]
@danielmarbach @mikeminutillo we can close this one also, right?

**Comment by danielmarbach** [comment]
Closing since we currently don't need such an API. We can reopen it if required

**Pull request closed without merging**
