### PR TITLE
Added ability to enter MaintenanceMode

### PR DESCRIPTION
**Pull request by johnsimons**
This PR addresses #735

Here is how this is going to work:
- User stops the endpoint instance;
- They then can click on "Start in Maintenance" button;
- Once they done the "Stop" the instance, and this will revert back to normal mode

Here is what is looking like so far:
image
image

### CODE REVIEW

**Comment by johnsimons** [comment]
@sergioc can we get an icon for the button "Start in Maintenance", something like the usual screwdriver cross ?

We also need the panel that says "This instance is in main...." prettied up :smile:

**Comment by johnsimons** [comment]
@gbiellem regarding this PR and #625, this won't address #625, to fix #625 we need to run the instance with the admin account that is running the installer right ?

**Comment by gbiellem** [comment]
I think we should address #625 before this goes out. 
The only reason an admin account is required for #625 is that we don't set a urlacl for /storage.  There is also some weirdness in the SC Raven Init icode that limits the.binding to local host for wild cards but not fully qualified domain names.  I think we need to get the user to be explicit about that binding rather than trying to determine it.  This would allow the use of Raven studio from a 2nd PC - that would address scenarios where silver light is not an option on the server as highlighted in #638

**Comment by sergioc** [comment]
- Is there a confirmation prompt that displays when switching to maintenance mode?

**Comment by johnsimons** [comment]
@sergioc nope

**Comment by johnsimons** [comment]
> The only reason an admin account is required for #625 is that we don't set a urlacl for /storage. There is also some weirdness in the SC Raven Init icode that limits the.binding to local host for wild cards but not fully qualified domain names. I think we need to get the user to be explicit about that binding rather than trying to determine it. This would allow the use of Raven studio from a 2nd PC - that would address scenarios where silver light is not an option on the server as highlighted in #638

@gbiellem can we discuss this a bit more, what exactly do we need to do ?

**Comment by johnsimons** [comment]
@gbiellem is [this](https://github.com/Particular/ServiceControl/blob/dd3db2a0ea66c6b35d1f44c43e7a685da62cbe3c/src/ServiceControl/Infrastructure/RavenDB/RavenBootstrapper.cs#L62-L64) what u talking about ?

**Comment by sergioc** [comment]
@johnsimons since the instance needs to be stopped before entering maintenance mode, shouldn't we have a prompt to allow the user confirm, just like we do for upgrades?

**Comment by johnsimons** [comment]
Sure we can do that

On Fri, 17 Jun 2016 at 18:27 Sergio <notifications@github.com> wrote:

> @johnsimons <https://github.com/johnsimons> since the instance needs to
> be stopped before entering maintenance mode, shouldn't we have a prompt to
> allow the user confirm, just like we do for upgrades?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Particular/ServiceControl/pull/747#issuecomment-226711204>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAHfG69g8_u4piNcad9w9ebKyqh0Haurks5qMlp5gaJpZM4I1BWu>
> .
>
-- 

*John Simons*
*Engineer, Particular Software*

Email*:*  john.simons@particular.net
Web:    www.particular.net

**Comment by sergioc** [comment]
> Sure we can do that

Excellent.

**Comment by sergioc** [comment]
Here's how SCMU could look like while in Maintenance Mode:

screenshot 2016-06-17 12 17 16

**Comment by johnsimons** [comment]
@sergioc can you give us the icon ?

**Comment by sergioc** [comment]
Icons: https://www.dropbox.com/sh/jvg7faw3i9a7274/AAA1QwX_Ldbtpjozjk-yABZ4a?dl=0

**Comment by johnsimons** [comment]
@gbiellem this is now ready, can u review it

Also, I think the url for raven is better in your PR ;)

**Comment by gbiellem** [comment]
Code looks good. Found the maint mode icon being greyed out a little weird initially but once I stopped the service it made sense

**Comment by johnsimons** [comment]
Awesome

**Comment by gbiellem** [comment]
@johnsimons Above you told @sergioc  that you'd add a confirmation dialog.  I think that would make sense on starting maintenance mode - it might be a good place to put some explaination of what this actually is and what it's for

**Comment by gbiellem** [comment]
Actually the confirmation you promised @sergioc was for stopping the instance so it's not exactly the 
same

**Comment by johnsimons** [comment]
@gbiellem 
yeah, the user has to stop the endpoint before they can start in maintenance mode.

but I agree, i think we need a bit more explanation what this is for, we can talk more about it tomorrow

**Comment by sergioc** [comment]
> yeah, the user has to stop the endpoint before they can start in maintenance mode.

That's why a confirmation prompt for starting is also useful. If the button is greyed out, how will the user understand that the instance has to be stopped first in order to be able to click that button?

Adding a confirmation prompt to start maintenance mode allows the button to be enabled. The prompt will then explain the instance has to be stopped first, which will be done automatically before entering maintenance mode once the user confirms.

**Pull request merged**
