### PR TITLE
Configure embedded RavenDB 5 to use the configured log directory of the audit instance

### PR DESCRIPTION
**Pull request by andreasohlund**
Fixes https://github.com/Particular/ServiceControl/issues/3364

### CODE REVIEW

**Comment by andreasohlund** [comment]
@mauroservienti @DavidBoike it seems like raven uses this path no matter what so that might explain why we couldn't change it using the `settings.json` file. I would assume things like loglevel would work using that approach but haven't tested

**Comment by andreasohlund** [comment]
>Well that’s good, that means we don’t have to worry about rewriting a JSON file if the SC configuration changes, right?

Yea

We do have https://docs.particular.net/servicecontrol/logging#logging-levels-versions-1-9-and-above that now is incorrect that would require a json file but we can handle that as a separate less urgent issue

**Comment by mikeminutillo** [comment]
I can confirm that the Raven Embedded source code [always sets a value](https://github.com/ravendb/ravendb/blob/v5.4/src/Raven.Embedded/ServerOptions.cs#L16) and [passes it on the command line](https://github.com/ravendb/ravendb/blob/v5.4/src/Raven.Embedded/RavenServerRunner.cs#L36). We cannot even [clear out the default](https://github.com/ravendb/ravendb/blob/v5.4/src/Raven.Embedded/RavenServerRunner.cs#L21-L22) so we must always set it.

**Comment by mikeminutillo** [comment]
I made a [slight tweak](https://github.com/Particular/ServiceControl/pull/3367/commits/0466488ea701271f3708fa947bd6dc75fe80b63a) to ensure that the config value is copied into the persister specific settings. Unfortunately the acceptance tests bypass this by using the same server instance for every test, and the persistence tests bypass it because they test below the configuration layer.

**Review by mikeminutillo — APPROVED** [review]

**Review by tmasternak — APPROVED** [review]

**Review by tmasternak — APPROVED** [review]

**Pull request merged**
