### PR TITLE
Update to Autofac 4.1.1 and NServiceBus.Autofac 5.1.1

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to https://github.com/Particular/docs.particular.net/pull/2024

To be honest this update is not strictly necessary. I figured I'll send it in nonetheless to see how the latest container changes would influence SC

### CODE REVIEW

**Comment by johnsimons** [comment]
So @danielmarbach you mean that if we decide to update to the latest version of the NServiceBus.Autofac then we also need to dispose of the container ?

**Comment by danielmarbach** [comment]
@johnsimons correct

**Comment by SimonCropp** [comment]
> So @danielmarbach you mean that if we decide to update to the latest version of the NServiceBus.Autofac then we also need to dispose of the container

then how is that a safe behaviour change to put in a patch?

**Comment by danielmarbach** [comment]
@SimonCropp discussed this with @andreasohlund @timbussmann and @Particular/container-maintainers and we treated it as a bug. Let's face it:

If a user owns a container and passed it into the bus configuration then that code becomes the composition root of the container. It is and always was the responsibility of the composition root to dispose disposables. Arguably if a user code doesn't dispose the created container the bug was always there in the user code and our wrong container adapter behavior made it sorta work but it never should have.

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceControl/commit/b8995d60ccfb1bae400b9d544344cbc3732321a2

**Pull request closed without merging**
