### PR TITLE
[WIP] Change sc access modifiers

### PR DESCRIPTION
**Pull request by boblangley**
Connects to #1354

Move types to internal in order to use APIApprovals for stabilizing public (both customer and Particular use only) contracts.

### CODE REVIEW

**Comment by boblangley** [comment]
53 acceptance tests are still failing.

**Comment by danielmarbach** [comment]
@boblangley why is it necessary to change the access modifiers of the Acceptance Tests?

**Comment by boblangley** [comment]
@danielmarbach So far because they expose previously public types. The first pass was very crude, I may have to reverse some of the access modifier changes.

**Comment by boblangley** [comment]
Closed in favor of #1421 which reorganizes these commits into something more reviewable.

**Pull request closed without merging**
