### PR TITLE
Merge Hotfix 3.3.4 back to develop

### PR DESCRIPTION
**Pull request by andreasohlund**
Note that this PR have some commits from previous hotfixes due to those merge backs likely being rebased when merged back.

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/servicecontrol-maintainers please review and merge

**Comment by andreasohlund** [comment]
@danielmarbach talking to Brandon the reason for the changed commits was likely due to the previous hotfixes being rebased before merge just like we suspected

**Comment by andreasohlund** [comment]
@bording something is still off here since 

https://github.com/Particular/ServiceControl/compare/develop...master

shows changes.

Should I open a new PR that merges master into develop to see if that gets us back in sync?

**Comment by bording** [comment]
@andreasohlund The reason there's still a problem is that this PR was squash merged, which should never be done for "merge back" PRs.

**Comment by andreasohlund** [comment]
I've merged master back now so we're all good

https://github.com/Particular/ServiceControl/compare/develop...master

**Pull request merged**
