### PR TITLE
Include RavenDB 3.5 persister in main instance docker images

### PR DESCRIPTION
**Pull request by andreasohlund**
I realized that when we adjusted how we package the main instance we broke the docker images. This should fix that.

### CODE REVIEW

**Comment by andreasohlund** [comment]
@mikeminutillo I think we do have a problem with check , see this PR as an example 
image

**Comment by andreasohlund** [comment]
@mauroservienti would you be able to test this one?

**Comment by mauroservienti** [comment]
Yes, I will

**Review by mikeminutillo — APPROVED** [review]

**Comment by mauroservienti** [comment]
Tested ✅

**Pull request merged**
