### PR TITLE
Remove ReplyToAddress and Migration tests since we force an upgrade to 2.1.x latest

### PR DESCRIPTION
**Pull request by danielmarbach**
Would address #1360

### CODE REVIEW

**Comment by mikeminutillo** [comment]
I wonder if we can remove some of the Migrations now too.
If you are on V2 then you've either run those migrations or you don't need to because you were never on an affected version.

**Comment by mikeminutillo** [comment]
Do we still need the property `FailedMessage.ProcessingAttempt.RetryAddress`?
If we drop it, does the storage just ignore it when it deserializes?

**Comment by WilliamBZA** [comment]
> I wonder if we can remove some of the Migrations now too.

I am 💯 behind doing so

**Comment by danielmarbach** [comment]
@mikeminutillo RavenDB is tolerant when reading records. So effectively old documents will be read without that property but not modified

**Comment by WilliamBZA** [comment]
The only bug-free code is deleted code

**Pull request merged**
