### PR TITLE
AdoptOrphanedBatches running more then necessary

### LINKED ISSUE #681: AdoptOrphanedBatches running more then necessary

### PR DESCRIPTION
**Pull request by johnsimons**
Fixes #681

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/servicecontrol-maintainers please review

**Comment by johnsimons** [comment]
@mikeminutillo please review it before monday

**Comment by mauroservienti** [comment]
If I understood everything correctly:

* when messages are retried, group of messages, they are retried in batches
* it may happen, e.g. SC is shut down while retrying, that one or more batch is orphaned 
* this process looks for orphans and if found restarts the retry batch, otherwise stops itself from looking for orphans
* before we were continuously looking for orphans 

If that's the case, then it looks fine and I cannot spot any smell in the code. @mikeminutillo last word to you :smile: , I'm :+1:

**Comment by mikeminutillo** [comment]
I'm usually against `out` params on `void` methods but in this case I think it makes it clearer what's going on. :+1: from me

**Comment by mikeminutillo** [comment]
This will all go away if we implement https://github.com/Particular/PlatformDevelopment/issues/635 ;)

**Pull request merged**
