### PR TITLE
add multi target framework

### PR DESCRIPTION
**Pull request by RoderickIveans**
I have done some simple work for cross platform
1.Updated some target frameworks
2.Move some code to simplify dependency

### CODE REVIEW

**Comment by ramonsmits** [comment]
@RoderickIveans The description is empty, could you share what your intent is of this PR? Besides doing a partial multi target its doing a few refactorings. We are in the process of upgrading our primary/error instance. After that we will likely target net6 too.

**Comment by RoderickIveans** [comment]
@ramonsmits I have updated

**Comment by RoderickIveans** [comment]
@ramonsmits May you review it?

**Comment by ramonsmits** [comment]
@RoderickIveans while we appreciate your effort we are closing this as there are multiple changes combined in this PR as well as unwanted refactorings and its currently out of date. We try to avoid using the latest language features.

Regarding multi targeting to get linux hosting. This is on our radar and will be done after we fully support RavenDB 5.x

**Pull request closed without merging**
