### PR TITLE
[WIP] Add monitoring service to Management UI

### PR DESCRIPTION
**Pull request by gbiellem**
Connects to https://github.com/Particular/ServiceControl/issues/979

Related to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/51

Incorporate Monitoring Serviice into SC management UI and Powershell as a deployable component

- [x] Change Packaging to include the output of ServiceControl.Monitoring from MyGet
- [x] Update management engine to handle deployment of a new service
- [x] Add Powershell cmdlets to Add/Delete/Upgrade/List Monitoring instances
- [x] Update Powershell local docs
- [x] ~Review unattended install (deprecate existing way?)~
- [x] Update Mgmt UI
  - [x]  Instances List View / Main View - @mikeminutillo
  - [x] Add/Edit Screens
  - [x] Upgrade wizard
  - [x] Advanced View (Handles delete )
  - [x] Validation
- [x] Review MSI Uninstall (Currenlty warns if SC services are present)

### CODE REVIEW

**Comment by gbiellem** [comment]
Requires an update of the SC Monitoring myget package once https://github.com/Particular/ServiceControl.Monitoring/pull/13 is merged.  Until then there will be a mismatch in UrlAcl and the LogPath setting will not work

**Comment by mikeminutillo** [comment]
Removed docs changes from this PR as they are covered by the parent issue

**Comment by WilliamBZA** [comment]
What is still outstanding here? The parent issue is already closed, surely the PR should be merged then?

**Comment by gbiellem** [comment]
@WilliamBZA  Aside from the merge conflicts the packages need updating before release so it's bundles the release version of the monitoring service.  Currently it's targeting an alpha build

https://github.com/Particular/ServiceControl/blob/Add-sc-monitoring-to-Installer/src/ServiceControlInstaller.Engine/packages.config

**Comment by mikeminutillo** [comment]
The PR remains parked until a version of ServicePulse is ready that can support monitoring instances.

**Comment by SzymonPobiega** [comment]
Since we now have the feature toggle, can I rebase and merge it to master? /cc @mikeminutillo

**Comment by mikeminutillo** [comment]
Rebased. Just smoke testing locally before I push.

**Comment by mikeminutillo** [comment]
Pushed. Once the build is green, this can be merged

**Comment by gbiellem** [comment]
@mikeminutillo   Oooh Shiny!... Does this mean monitoring is going to ship soon

**Comment by WilliamBZA** [comment]
@gbiellem aasd

**Comment by gbiellem** [comment]
ROFL - Nice one @WilliamBZA

**Pull request merged**
