### PR TITLE
SagaHistory tests

### PR DESCRIPTION
**Pull request by danielmarbach**
Addresses https://github.com/Particular/ServiceControl/pull/1069#discussion_r168081712

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/servicecontrol-maintainers @SeanFeldman @WilliamBZA please review and merge

**Comment by WilliamBZA** [comment]
Pinging @boblangley and @SzymonPobiega too

**Comment by SeanFeldman** [comment]
The test is failing every single transport with timeout error.
How do we proceed?

**Comment by SeanFeldman** [comment]
The test is passing locally. On the build server, fails beacuse of the execution timeout and not failing assertion. Which indicates that RavenDB has not indexed the data we are looking for. Looking at the changes, there's nothing that would cause the failing tests we observe. Merging.

**Pull request merged**
