### PR TITLE
Don't create forwarding queues if option is disabled

### PR DESCRIPTION
**Pull request by gbiellem**
Related to #849

When adding a new instance and forwarding is turned off don't create the queues.  

### Mgmt UI Changes

The Add Instance UI will only ask and validate Error forwarding queue name or Audit Forwarding queue name if that related combo box is "on"

The Edit Instance screen will feature switch because of the different behavior in old versions.  
 - For version prior to 1.12 the forwarding queues are always displayed and the ErrorForwarding combo is not shown
 - For version 1.12 to the version prior to this release the ErrorForwarding combo is always shown and the  forwarding queues are always displayed and created
- For this version and above forwarding queues are only displayed 

### Mgmt PowerShell Changes.  

Cmdlets for adding ServiceControl instances no longer require the forwarding queue name if the forwarding option is off

### Config changes

For new ServiceControl instances or ServiceControl instances upgraded by this release:

- the 'ServiceBus/ErrorLogQueue' is omitted if 'ServiceControl/ForwardErrorMessages' is set to 'false'
- the 'ServiceBus/AuditLogQueue' is omitted if 'ServiceControl/ForwardAuditMessages' is set to 'false'

### ServiceControl service changes

- The queue creation for forwarding queues durign setup is only executed if the forwarding is enabled
- The empty test message sent to the forwarding queues at startup has been removed

### CODE REVIEW

**Comment by gbiellem** [comment]
@johnsimons  review?

**Comment by johnsimons** [comment]
so small 😲

**Comment by gbiellem** [comment]
Yeah I know... It sounded so simple in #849 when first proposed and it looks more complicated than it is.
Most of the changes are due to the edit and add screens sharing a base class. I've moved large chunks out of the common model to accommodate the change.  Which means I also had to move chunks of validation etc...

**Comment by johnsimons** [comment]
@gbiellem I don't think this is related to this change but if I shrink the width of the form the text gets chopped:
image

**Comment by johnsimons** [comment]
Also, I wonder if it would be possible to make the gap between the fields and the warning smaller ?
image

**Comment by gbiellem** [comment]
@johnsimons  good pickup on both counts - I'll take a look

**Comment by johnsimons** [comment]
fields are not lined up
image

**Comment by johnsimons** [comment]
The tab order stops on the warning icon 
image

**Comment by gbiellem** [comment]
@johnsimons  Can't repro the alignment issue.  A little help please.

alignment

**Comment by johnsimons** [comment]
@gbiellem how come we still need UI\SharedInstanceEditor\SharedInstanceEditorView.xaml.cs ?

**Comment by gbiellem** [comment]
@johnsimons I was trying to only change what was necessary for this fix.  As you already noted it was already getting big.

**Comment by johnsimons** [comment]
Everything else looks ok to me

**Comment by gbiellem** [comment]
Cool. OK to merge then?

**Pull request merged**
