### PR TITLE
Disabled reimporting; logging warn if there are errors that failed to import

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@gbiellem @indualagarsamy Here's the hotfix pull. Please review.

**Comment by gbiellem** [comment]
@SzymonPobiega I think this can be shipped,  Can you update/close the issue?

**Comment by SzymonPobiega** [comment]
Close issue? You mean release 1.5.1?

**Comment by gbiellem** [comment]
@SzymonPobiega  i assumed  https://github.com/Particular/ServiceControl/issues/445 should be updated to  reflect what you've done and then closed right? Once that's done i can release or you can do it.

**Pull request merged**
