### PR TITLE
Update stack trace regex parsing to support failed case

### PR DESCRIPTION
**Pull request by WilliamBZA**
Connects to https://github.com/Particular/ServiceControl/issues/919

* Updates the stack trace parser regex to work with the failing case
* Adds an additional test to validate the fix

Ping @Particular/servicecontrol-maintainers

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Another option is to remove the regex completely as we only ever use the first stackframe and not all of them. If we can validate that assumption then perhaps we can come up with a non-regex based solution that doesn't look like black magic.. @mikeminutillo Do you know enough about this piece of code to confirm the assumption?

**Comment by WojcikMike** [comment]
I've spent some time reviewing the changes the botom line is that it replaces:
 - \s with [\x20\t] //which is space (ascii 32) or tab
 - . with [^\x20\t] //which is everything beside above

In theory \s represents: [\r\n\t\f\v ] (I found it on some site) so it include more than only space and tab. yet the change seems to work correctly. Looking at the [StackTraceParser repo](https://github.com/atifaziz/StackTraceParser)
They found this issue: https://github.com/atifaziz/StackTraceParser/issues/2 which resulted in the same change being made. However the issue found there is incorrect parsing of the stacktrace rather than 100 % CPU utilization. 

cc: @mikeminutillo @janovesk

**Comment by janovesk** [comment]
Looks good to me, but then again.. I'm no expert at regex! Replacing with custom parsing is a nightmare though, so I would keep this.

 Maybe we should consider pulling in the Nuget source package instead, https://github.com/atifaziz/StackTraceParser?

**Comment by WilliamBZA** [comment]
@janovesk @WojcikMike I've updated to use the nuget package directly.

If you're happy please approve and I'll merge and release.

**Comment by WojcikMike** [comment]
@WilliamBZA approved.

**Pull request merged**
