### PR TITLE
Modify `GetErrorById` to return data in similar format as `GetAllErrors`

### PR DESCRIPTION
**Pull request by WojcikMike**
Modify `GetErrorById` to return data in similar format as `GetAllErrors`

### CODE REVIEW

**Comment by WojcikMike** [comment]
@Particular/servicecontrol-maintainers can someone have a look at this?

**Comment by johnsimons** [comment]
I have no issues with this change, just confirming with @Particular/serviceinsight-maintainers to make sure it does not affect it.

**Comment by HEskandari** [comment]
From ServiceInsight perspective, at the moment we don't use the response from the 'retry' endpoint so changing the return type would not be an issue. There's also no strict 'contract' or proxy objects that'd need regenerating, so it LGTM.

With all said, I'd like to test ServiceInsight with the updated version of ServiceControl to absolutely make sure it works fine.

**Comment by HEskandari** [comment]
I stand corrected, we don't use this specific API at all, we use the Retry one at /errors/{id}/retry. Feel free to change this as it has no impact on ServiceInsight.

**Comment by WojcikMike** [comment]
In that case please merge @Particular/servicecontrol-maintainers if you are satisfied with the code

**Comment by WojcikMike** [comment]
@johnsimons I assume that this PR will be released with any next feature that will be released right?

**Pull request merged**
