### PR TITLE
[WIP] Flake ATT investigation

### PR DESCRIPTION
**Pull request by andreasohlund**
Not to be merged

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@andreasohlund all the ATTs are passing on a build directly from this branch http://builds.particular.net/viewLog.html?buildId=104411&tab=buildResultsDiv&buildTypeId=bt58

**Comment by andreasohlund** [comment]
Vierd, the pure develop branch is failing rght?

**Comment by SzymonPobiega** [comment]
Yes.

**Comment by synhershko** [comment]
@SzymonPobiega that would depend on how the result looks like. `Join(", ", ...)` would have worked for sure. StandardTokenizer has some smarts to preserve stuff like IP addresses etc, this may be it.

**Comment by johnsimons** [comment]
Superseded by #486

**Pull request closed without merging**
