### PR TITLE
Provide information to visitors

### PR DESCRIPTION
**Pull request by boblangley**
Looking at https://github.com/Particular/ServiceControl/graphs/traffic most of our visitors come to the main page, and many from searches. We should have some basic links to help them find what they may be looking for.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Why [WIP]?

**Comment by boblangley** [comment]
I am not done yet.

**Comment by boblangley** [comment]
Now I am done ;) @Particular/servicecontrol-maintainers please review. Feel free to improve if I have missed anything obvious.

**Comment by WilliamBZA** [comment]
It'd be really interesting if we could eliminate members of the Particular organisation from those graphs somehow 😄 

Great job. Looks good to me. I'm going to merge.

**Pull request merged**
