### PR TITLE
Added warning about forwarding queues

### PR DESCRIPTION
**Pull request by johnsimons**
This addresses #766

### CODE REVIEW

**Comment by johnsimons** [comment]
@gbiellem want to review this one ?

**Comment by gbiellem** [comment]
@johnsimons LGTM. I made the warnings contextual so they only show when the options are on.  I believe that what @sergioc wanted.

**Comment by sergioc** [comment]
Behavior is 👍 . However, the warning text is a bit cramped and the yellow text makes it a bit harder to read:

screenshot 2016-08-22 09 21 22

I've mocked up a version with black text, more white space, better alignment and a shortened message:

screenshot 2016-08-22 09 36 55

**Comment by gbiellem** [comment]
Thanks @sergioc I'll adjust it

**Comment by sergioc** [comment]
@gbiellem if we have documentation about why should Audit Forwarding remain OFF if that queue is not being processed, I suggest adding a "Learn more" link at the end of the text linking to the documentation page.

**Comment by gbiellem** [comment]
@sergioc 

Not sure about that, I believe we usually try to steer clear of deep linking to docs within the products

**Comment by sergioc** [comment]
> Not sure about that, I believe we usually try to steer clear of deep linking to docs within the products

Why? It would provide more context to the warning. Otherwise you either leave the user wondering about why or you have to resort to lengthy messages in the UI.

**Comment by gbiellem** [comment]
@sergioc tweaks made. 

capture

I won't add a link because
-  the message is pretty self explanatory -
- as I've stated we don't deep link to docs.  

I believe the reason we don't deep link is that by anchoring this to a version of a page in docs we are then bound to maintain that URL and the relevance of the content for the life of this version of the product.  So effectivley we'd expect it to be a permalink

**Comment by gbiellem** [comment]
@johnsimons  review and merge if you are happy

**Comment by sergioc** [comment]
Makes sense why we don't deep link. However, that doesn't mean we should leave the user with questions unanswered and no clue about where to find the answer.

> the message is pretty self explanatory

@gbiellem as a user I'd ask "why is it telling me to enable in those circumstances?". How about creating a modal with the full explanation, accessible via a "Learn more" or "More information" link?

**Comment by gbiellem** [comment]
@sergioc I'm struggling to see what is vague in the message.  Anyone who is installing this is setting it up to monitor queues so they'll have a basic understanding on message queuing. It makes perfect sense to not send messages to a queue if nothing is processing them. The end result is at best a waste of disk space and at worst out of disk space/queue resources.

**Comment by gbiellem** [comment]
If you do think it is still vague I'd suggest we actually re work the form and make a section called something like External Integration and put all the Forwarding configuration under that with an overarching blurb on what the forwarding queues are

**Comment by gbiellem** [comment]
@indualagarsamy  Any thoughts since you raised the original issue this PR is trying to addresses

**Comment by sergioc** [comment]
> If you do think it is still vague I'd suggest we actually re work the form and make a section called something like External Integration and put all the Forwarding configuration under that with an overarching blurb on what the forwarding queues are

I'd definitely not hold up merging this in order to do what you suggest since what's done already constitutes an improvement. The UI should not be cluttered with too much explanation text either.

I'm just concerned that users might not understand why we're issuing that warning, because the cause may not seem explicit. We'd only be able to figure this out during a user test, though. So I'd release this as-is, then later assess in a test.

**Comment by gbiellem** [comment]
@sergioc  :+1:  - I'd still like to get @indualagarsamy to review before we merge though since she raised the original issue

**Comment by indualagarsamy** [comment]
@gbiellem - I like the changes you made. 👍 for merging.

**Pull request merged**
