### PR TITLE
Do deletes outside paging

### PR DESCRIPTION
**Pull request by johnsimons**
Otherwise the paging numbers change and it becomes much harder to recalculate

### CODE REVIEW

**Comment by johnsimons** [comment]
@mikeminutillo I think this is it ?

**Comment by tmasternak** [comment]
@johnsimons is this fixing statistics or is it a fix to the logic?

**Comment by mikeminutillo** [comment]
It fixes a bug in the pagination. It should go in before sending the email.

The code looks right to me @johnsimons 

My only concern here is that by not deleting the old document in the same session as we create the new ones we might fail part way through a migration and have a bunch of FailedMessage documents lying around with no ProcessingAttempts on them. 

Having said that, if we fail partway through a migration, SC won't finish the update process.

**Comment by mikeminutillo** [comment]
@johnsimons Are we going to make this 1.28 or do we release 1.27.1?

**Comment by johnsimons** [comment]
> or do we release 1.27.1?

what is that ? You know we don't do those 😉

**Comment by mikeminutillo** [comment]
Well in this case I thought we might make an exception as the only thing going in to a release a bug fix to a fix that was added to the previous release.

**Comment by johnsimons** [comment]
@mikeminutillo 
no is not https://github.com/Particular/ServiceControl/milestone/69

**Comment by johnsimons** [comment]
the train always rolls forward

**Pull request merged**
